<a href="https://colab.research.google.com/github/SOwens-Create/BabyPython/blob/master/QuizOneAIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd


In [9]:
demo_array = np.arange(10,21)
subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [10]:
demo_matrix = np.array([[13,35,74,48], [23,37,37,38],[73,39,93,39]])
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [11]:
test_array = np.array([1,2,3,4,5,6,7,8,9,10]) 
bool = test_array > 5
bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
              16,17,18,19,20,21,22,23,24,25,26,27,28,29])
array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [30]:
df = pd.read_csv('/content/drive/MyDrive/Wine.csv')
df.loc[[2,3],['magnesium', 'total_phenols']]

magnesium  total_phenols
2        101           2.80
3        113           3.85

In [33]:
df['alcalinity_of_ash'].mean()

19.49494382022472

In [34]:
def edit_col(col):
    col = col*2 + 10
    return col

df.malic_acid.apply(edit_col)

0      13.42
1      13.56
2      14.72
3      13.90
4      15.18
       ...  
173    21.30
174    17.82
175    18.56
176    15.18
177    18.20
Name: malic_acid, Length: 178, dtype: float64

In [37]:
df.sort_values(by = 'total_phenols')

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
146    13.88        5.04  2.23               20.0         80           0.98   
70     12.29        1.61  2.21               20.4        103           1.10   
132    12.81        2.31  2.40               24.0         98           1.15   
170    12.20        3.03  2.32               19.0         96           1.25   
165    13.73        4.36  2.26               22.5         88           1.28   
..       ...         ...   ...                ...        ...            ...   
58     13.72        1.43  2.50               16.7        108           3.40   
63     12.37        1.13  2.16               19.0         87           3.50   
98     12.37        1.07  2.10               18.5         88           3.52   
3      14.37        1.95  2.50               16.8        113           3.85   
52     13.82        1.75  2.42               14.0        111           3.88   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity  \
146        0.34                  0.40             0.68             4.90   
70         1.02                  0.37             1.46             3.05   
132        1.09                  0.27             0.83             5.70   
170        0.49                  0.40             0.73             5.50   
165        0.47                  0.52             1.15             6.62   
..          ...                   ...              ...              ...   
58         3.67                  0.19             2.04             6.80   
63         3.10                  0.19             1.87             4.45   
98         3.75                  0.24             1.95             4.50   
3          3.49                  0.24             2.18             7.80   
52         3.74                  0.32             1.87             7.05   

       hue  od280/od315_of_diluted_wines  proline  
146  0.580                          1.33      415  
70   0.906                          1.82      870  
132  0.660                          1.36      560  
170  0.660                          1.83      510  
165  0.780                          1.75      520  
..     ...                           ...      ...  
58   0.890                          2.87     1285  
63   1.220                          2.87      420  
98   1.040                          2.77      660  
3    0.860                          3.45     1480  
52   1.010                          3.26     1190  

[178 rows x 13 columns]

In [38]:
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [42]:
df.to_csv("df.csv", index = True)

In [41]:
df.to_csv(index = True)

',alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline\n0,14.23,1.71,2.43,15.6,127,2.8,3.06,0.28,2.29,5.64,1.04,3.92,1065\n1,13.2,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.4,1050\n2,13.16,2.36,2.67,18.6,101,2.8,3.24,0.3,2.81,5.68,1.03,3.17,1185\n3,14.37,1.95,2.5,16.8,113,3.85,3.49,0.24,2.18,7.8,0.86,3.45,1480\n4,13.24,2.59,2.87,21.0,118,2.8,2.69,0.39,1.82,4.32,1.04,2.93,735\n5,14.2,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450\n6,14.39,1.87,2.45,14.6,96,2.5,2.52,0.3,1.98,5.25,1.02,3.58,1290\n7,14.06,2.15,2.61,17.6,121,2.6,2.51,0.31,1.25,5.05,1.06,3.58,1295\n8,14.83,1.64,2.17,14.0,97,2.8,2.98,0.29,1.98,5.2,1.08,2.85,1045\n9,13.86,1.35,2.27,16.0,98,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045\n10,14.1,2.16,2.3,18.0,105,2.95,3.32,0.22,2.38,5.75,1.25,3.17,1510\n11,14.12,1.48,2.32,16.8,95,2.2,2.43,0.26,1.57,5.0,1.17,2.82,1280\n12,13.75,1.73,2.41,16.0,89,2.6,2